// Autogenerated from Pigeon (v29.0.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.pocketcinema.app.platform

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object StorageApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class AuthorizedRootMessage (
  val treeUri: String,
  val displayName: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AuthorizedRootMessage {
      val treeUri = pigeonVar_list[0] as String
      val displayName = pigeonVar_list[1] as String
      return AuthorizedRootMessage(treeUri, displayName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      treeUri,
      displayName,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AuthorizedRootMessage
    return StorageApiPigeonUtils.deepEquals(this.treeUri, other.treeUri) && StorageApiPigeonUtils.deepEquals(this.displayName, other.displayName)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.treeUri)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.displayName)
    return result
  }
  override fun toString(): String {
    return "AuthorizedRootMessage(treeUri=$treeUri, displayName=$displayName)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RootAccessMessage (
  val state: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RootAccessMessage {
      val state = pigeonVar_list[0] as String
      return RootAccessMessage(state)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RootAccessMessage
    return StorageApiPigeonUtils.deepEquals(this.state, other.state)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.state)
    return result
  }
  override fun toString(): String {
    return "RootAccessMessage(state=$state)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class StorageEntryMessage (
  val storageKey: String,
  val parentStorageKey: String? = null,
  val relativePath: String,
  val displayName: String,
  val isDirectory: Boolean,
  val mimeType: String? = null,
  val sizeBytes: Long? = null,
  val modifiedAtEpochMs: Long? = null,
  val flags: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StorageEntryMessage {
      val storageKey = pigeonVar_list[0] as String
      val parentStorageKey = pigeonVar_list[1] as String?
      val relativePath = pigeonVar_list[2] as String
      val displayName = pigeonVar_list[3] as String
      val isDirectory = pigeonVar_list[4] as Boolean
      val mimeType = pigeonVar_list[5] as String?
      val sizeBytes = pigeonVar_list[6] as Long?
      val modifiedAtEpochMs = pigeonVar_list[7] as Long?
      val flags = pigeonVar_list[8] as Long
      return StorageEntryMessage(storageKey, parentStorageKey, relativePath, displayName, isDirectory, mimeType, sizeBytes, modifiedAtEpochMs, flags)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      storageKey,
      parentStorageKey,
      relativePath,
      displayName,
      isDirectory,
      mimeType,
      sizeBytes,
      modifiedAtEpochMs,
      flags,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as StorageEntryMessage
    return StorageApiPigeonUtils.deepEquals(this.storageKey, other.storageKey) && StorageApiPigeonUtils.deepEquals(this.parentStorageKey, other.parentStorageKey) && StorageApiPigeonUtils.deepEquals(this.relativePath, other.relativePath) && StorageApiPigeonUtils.deepEquals(this.displayName, other.displayName) && StorageApiPigeonUtils.deepEquals(this.isDirectory, other.isDirectory) && StorageApiPigeonUtils.deepEquals(this.mimeType, other.mimeType) && StorageApiPigeonUtils.deepEquals(this.sizeBytes, other.sizeBytes) && StorageApiPigeonUtils.deepEquals(this.modifiedAtEpochMs, other.modifiedAtEpochMs) && StorageApiPigeonUtils.deepEquals(this.flags, other.flags)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.storageKey)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.parentStorageKey)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.relativePath)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.displayName)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.isDirectory)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.mimeType)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.sizeBytes)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.modifiedAtEpochMs)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.flags)
    return result
  }
  override fun toString(): String {
    return "StorageEntryMessage(storageKey=$storageKey, parentStorageKey=$parentStorageKey, relativePath=$relativePath, displayName=$displayName, isDirectory=$isDirectory, mimeType=$mimeType, sizeBytes=$sizeBytes, modifiedAtEpochMs=$modifiedAtEpochMs, flags=$flags)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SmallFileMessage (
  val bytes: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SmallFileMessage {
      val bytes = pigeonVar_list[0] as ByteArray
      return SmallFileMessage(bytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      bytes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SmallFileMessage
    return StorageApiPigeonUtils.deepEquals(this.bytes, other.bytes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.bytes)
    return result
  }
  override fun toString(): String {
    return "SmallFileMessage(bytes=${bytes.contentToString()})"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlaybackLeaseMessage (
  val leaseId: String,
  val sourceUri: String,
  val strategy: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlaybackLeaseMessage {
      val leaseId = pigeonVar_list[0] as String
      val sourceUri = pigeonVar_list[1] as String
      val strategy = pigeonVar_list[2] as String
      return PlaybackLeaseMessage(leaseId, sourceUri, strategy)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      leaseId,
      sourceUri,
      strategy,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlaybackLeaseMessage
    return StorageApiPigeonUtils.deepEquals(this.leaseId, other.leaseId) && StorageApiPigeonUtils.deepEquals(this.sourceUri, other.sourceUri) && StorageApiPigeonUtils.deepEquals(this.strategy, other.strategy)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.leaseId)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.sourceUri)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.strategy)
    return result
  }
  override fun toString(): String {
    return "PlaybackLeaseMessage(leaseId=$leaseId, sourceUri=$sourceUri, strategy=$strategy)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ProbeResultMessage (
  val durationMs: Long? = null,
  val containerFormat: String? = null,
  val width: Long? = null,
  val height: Long? = null,
  val rotationDegrees: Long? = null,
  val videoCodec: String? = null,
  val audioCodecSummary: String? = null,
  val streamCount: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProbeResultMessage {
      val durationMs = pigeonVar_list[0] as Long?
      val containerFormat = pigeonVar_list[1] as String?
      val width = pigeonVar_list[2] as Long?
      val height = pigeonVar_list[3] as Long?
      val rotationDegrees = pigeonVar_list[4] as Long?
      val videoCodec = pigeonVar_list[5] as String?
      val audioCodecSummary = pigeonVar_list[6] as String?
      val streamCount = pigeonVar_list[7] as Long
      return ProbeResultMessage(durationMs, containerFormat, width, height, rotationDegrees, videoCodec, audioCodecSummary, streamCount)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      durationMs,
      containerFormat,
      width,
      height,
      rotationDegrees,
      videoCodec,
      audioCodecSummary,
      streamCount,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ProbeResultMessage
    return StorageApiPigeonUtils.deepEquals(this.durationMs, other.durationMs) && StorageApiPigeonUtils.deepEquals(this.containerFormat, other.containerFormat) && StorageApiPigeonUtils.deepEquals(this.width, other.width) && StorageApiPigeonUtils.deepEquals(this.height, other.height) && StorageApiPigeonUtils.deepEquals(this.rotationDegrees, other.rotationDegrees) && StorageApiPigeonUtils.deepEquals(this.videoCodec, other.videoCodec) && StorageApiPigeonUtils.deepEquals(this.audioCodecSummary, other.audioCodecSummary) && StorageApiPigeonUtils.deepEquals(this.streamCount, other.streamCount)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.durationMs)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.containerFormat)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.width)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.height)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.rotationDegrees)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.videoCodec)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.audioCodecSummary)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.streamCount)
    return result
  }
  override fun toString(): String {
    return "ProbeResultMessage(durationMs=$durationMs, containerFormat=$containerFormat, width=$width, height=$height, rotationDegrees=$rotationDegrees, videoCodec=$videoCodec, audioCodecSummary=$audioCodecSummary, streamCount=$streamCount)"
  }
}
private open class StorageApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AuthorizedRootMessage.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RootAccessMessage.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StorageEntryMessage.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SmallFileMessage.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlaybackLeaseMessage.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProbeResultMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AuthorizedRootMessage -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is RootAccessMessage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is StorageEntryMessage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is SmallFileMessage -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is PlaybackLeaseMessage -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is ProbeResultMessage -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface StorageHostApi {
  suspend fun chooseDirectory(): AuthorizedRootMessage
  fun listPersistedPermissions(): List<AuthorizedRootMessage>
  fun checkRoot(treeUri: String): RootAccessMessage
  fun startScan(treeUri: String, scanId: String, batchSize: Long)
  fun cancelScan(scanId: String)
  fun readSmallFile(treeUri: String, storageKey: String, maximumBytes: Long): SmallFileMessage
  fun openPlaybackSource(treeUri: String, storageKey: String, strategy: String): PlaybackLeaseMessage
  fun closePlaybackSource(leaseId: String)
  fun probeFile(treeUri: String, storageKey: String): ProbeResultMessage
  fun releasePermission(treeUri: String)

  companion object {
    /** The codec used by StorageHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      StorageApiPigeonCodec()
    }
    /** Sets up an instance of `StorageHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: StorageHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      val taskQueue = binaryMessenger.makeBackgroundTaskQueue()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pocket_cinema.StorageHostApi.chooseDirectory$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.chooseDirectory())
              } catch (exception: Throwable) {
                StorageApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pocket_cinema.StorageHostApi.listPersistedPermissions$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.listPersistedPermissions())
            } catch (exception: Throwable) {
              StorageApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pocket_cinema.StorageHostApi.checkRoot$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val treeUriArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.checkRoot(treeUriArg))
            } catch (exception: Throwable) {
              StorageApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pocket_cinema.StorageHostApi.startScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val treeUriArg = args[0] as String
            val scanIdArg = args[1] as String
            val batchSizeArg = args[2] as Long
            val wrapped: List<Any?> = try {
              api.startScan(treeUriArg, scanIdArg, batchSizeArg)
              listOf(null)
            } catch (exception: Throwable) {
              StorageApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pocket_cinema.StorageHostApi.cancelScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val scanIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.cancelScan(scanIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              StorageApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pocket_cinema.StorageHostApi.readSmallFile$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val treeUriArg = args[0] as String
            val storageKeyArg = args[1] as String
            val maximumBytesArg = args[2] as Long
            val wrapped: List<Any?> = try {
              listOf(api.readSmallFile(treeUriArg, storageKeyArg, maximumBytesArg))
            } catch (exception: Throwable) {
              StorageApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pocket_cinema.StorageHostApi.openPlaybackSource$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val treeUriArg = args[0] as String
            val storageKeyArg = args[1] as String
            val strategyArg = args[2] as String
            val wrapped: List<Any?> = try {
              listOf(api.openPlaybackSource(treeUriArg, storageKeyArg, strategyArg))
            } catch (exception: Throwable) {
              StorageApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pocket_cinema.StorageHostApi.closePlaybackSource$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val leaseIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.closePlaybackSource(leaseIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              StorageApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pocket_cinema.StorageHostApi.probeFile$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val treeUriArg = args[0] as String
            val storageKeyArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.probeFile(treeUriArg, storageKeyArg))
            } catch (exception: Throwable) {
              StorageApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.pocket_cinema.StorageHostApi.releasePermission$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val treeUriArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.releasePermission(treeUriArg)
              listOf(null)
            } catch (exception: Throwable) {
              StorageApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
